version: '3'
services:
    nodejs_app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./config.json:/config.json
            - ./stats.json:/stats.json
